### ISSUE TITLE
PSR-3 Logging support

### ISSUE THREAD

**Issue by jacobkiers** [marcelog/PAGI#30]
Hi Marcelo,

Now PSR-3 logging is merged in PAMI, I can work on PSR-3 support here in PAGI [as said in the original PR on PAMI](https://github.com/marcelog/PAMI/pull/74#issuecomment-93546240). Are you still interested in that?

Since I have carried patches for that for a long time in my own branch, it is probably not that much work to extract them and create a PR for it.

Please let me know.

Thanks, Jacob

**Comment by marcelog** [comment]
Absolutely :) Thank you!

**Comment by marcelog** [comment]
Please open the pull request for the branch 1.12.0, I will also the changes we did in PAMI to deprecate PEAR to this new branch.

**Comment by marcelog** [comment]
Closed with new v2.0.0 version @1ca5492622289569e78dc007d4aec99ed0dc56a5
