### ISSUE TITLE
White Space

### ISSUE THREAD

**Issue by dotcomva** [marcelog/PAGI#37]
agi vars had white space. Added trim to readEnvironmentVariable on line 722 in AbstractClient.php. trim($value)

**Comment by marcelog** [comment]
Please open a pull request instead of an issue if you want to merge a change. Also please also explain the use case and what creates the need exactly.

Cheers,

**Comment by dotcomva** [comment]
Will do. Good Job by the way.
Doing a db lookup on dialed extension, and incoming, and was getting white space at the beginning of the var.
Example:
$dialed = trim($vars->getDNID());
